common:

api_service:
  # create_log_dir: True
  # logfile: "record.txt"
  jwt_secret: abc
  jwt_salt: 123
  verbose: 1

  uvicorn:
    host: "0.0.0.0"
    port: "8000"
    log_level: debug
    workers: 1

  persistence:
    ORM: sqlalchemy
    db: postgresql 
    user: xxxx
    password: "123557"
    host: "host.docker.internal"
    db_name: fdksuirew
    port: "5432"
    ssl: False

  nosql:
    db: redis
    url_schema: redis
    host: "dsacxz"
    port: "1373714"
    username: None
    password: "xxxxad"
    db_num: 0
    ssl: False
    ssl_ca_certs: None
    health_check_interval: 1